/* This file was generated by PyBindGen 0.16.0 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stddef.h>


#if PY_VERSION_HEX < 0x020400F0

#define PyEval_ThreadsInitialized() 1

#define Py_CLEAR(op)				\
        do {                            	\
                if (op) {			\
                        PyObject *tmp = (PyObject *)(op);	\
                        (op) = NULL;		\
                        Py_DECREF(tmp);		\
                }				\
        } while (0)


#define Py_VISIT(op)							\
        do { 								\
                if (op) {						\
                        int vret = visit((PyObject *)(op), arg);	\
                        if (vret)					\
                                return vret;				\
                }							\
        } while (0)

#endif



#if PY_VERSION_HEX < 0x020500F0

typedef int Py_ssize_t;
# define PY_SSIZE_T_MAX INT_MAX
# define PY_SSIZE_T_MIN INT_MIN
typedef inquiry lenfunc;
typedef intargfunc ssizeargfunc;
typedef intobjargproc ssizeobjargproc;

#endif


#if     __GNUC__ > 2
# define PYBINDGEN_UNUSED(param) param __attribute__((__unused__))
#elif     __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4)
# define PYBINDGEN_UNUSED(param) __attribute__((__unused__)) param
#else
# define PYBINDGEN_UNUSED(param) param
#endif  /* !__GNUC__ */

typedef enum _PyBindGenWrapperFlags {
   PYBINDGEN_WRAPPER_FLAG_NONE = 0,
   PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED = (1<<0),
} PyBindGenWrapperFlags;


#include "dynamixel.h"
static PyMethodDef dynamixel_std_functions[] = {
    {NULL, NULL, 0, NULL}
};

static PyObject *
initdynamixel_std(void)
{
    PyObject *m;
    m = Py_InitModule3((char *) "dynamixel.std", dynamixel_std_functions, NULL);
    if (m == NULL) {
        return NULL;
    }
    return m;
}
/* --- module functions --- */


PyObject *
_wrap_dynamixel_dxl_read_word(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int id;
    int address;
    const char *keywords[] = {"id", "address", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "ii", (char **) keywords, &id, &address)) {
        return NULL;
    }
    retval = dxl_read_word(id, address);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_read_word(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_write_word(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int id;
    int address;
    int value;
    const char *keywords[] = {"id", "address", "value", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "iii", (char **) keywords, &id, &address, &value)) {
        return NULL;
    }
    dxl_write_word(id, address, value);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_write_word(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_txrx_packet()
{
    PyObject *py_retval;

    dxl_txrx_packet();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_txrx_packet();


PyObject *
_wrap_dynamixel_dxl_get_lowbyte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int word;
    const char *keywords[] = {"word", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &word)) {
        return NULL;
    }
    retval = dxl_get_lowbyte(word);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_lowbyte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_get_rxpacket_parameter(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int index;
    const char *keywords[] = {"index", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &index)) {
        return NULL;
    }
    retval = dxl_get_rxpacket_parameter(index);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_rxpacket_parameter(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_read_byte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int id;
    int address;
    const char *keywords[] = {"id", "address", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "ii", (char **) keywords, &id, &address)) {
        return NULL;
    }
    retval = dxl_read_byte(id, address);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_read_byte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_get_rxpacket_length()
{
    PyObject *py_retval;
    int retval;

    retval = dxl_get_rxpacket_length();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_rxpacket_length();


PyObject *
_wrap_dynamixel_dxl_write_byte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int id;
    int address;
    int value;
    const char *keywords[] = {"id", "address", "value", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "iii", (char **) keywords, &id, &address, &value)) {
        return NULL;
    }
    dxl_write_byte(id, address, value);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_write_byte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_get_result()
{
    PyObject *py_retval;
    int retval;

    retval = dxl_get_result();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_result();


PyObject *
_wrap_dynamixel_dxl_set_txpacket_length(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int length;
    const char *keywords[] = {"length", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &length)) {
        return NULL;
    }
    dxl_set_txpacket_length(length);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_set_txpacket_length(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_tx_packet()
{
    PyObject *py_retval;

    dxl_tx_packet();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_tx_packet();


PyObject *
_wrap_dynamixel_dxl_get_highbyte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int word;
    const char *keywords[] = {"word", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &word)) {
        return NULL;
    }
    retval = dxl_get_highbyte(word);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_highbyte(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_ping(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int id;
    const char *keywords[] = {"id", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &id)) {
        return NULL;
    }
    dxl_ping(id);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_ping(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_set_txpacket_id(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int id;
    const char *keywords[] = {"id", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &id)) {
        return NULL;
    }
    dxl_set_txpacket_id(id);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_set_txpacket_id(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_makeword(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int lowbyte;
    int highbyte;
    const char *keywords[] = {"lowbyte", "highbyte", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "ii", (char **) keywords, &lowbyte, &highbyte)) {
        return NULL;
    }
    retval = dxl_makeword(lowbyte, highbyte);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_makeword(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_terminate()
{
    PyObject *py_retval;

    dxl_terminate();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_terminate();


PyObject *
_wrap_dynamixel_dxl_set_txpacket_instruction(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int instruction;
    const char *keywords[] = {"instruction", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &instruction)) {
        return NULL;
    }
    dxl_set_txpacket_instruction(instruction);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_set_txpacket_instruction(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_get_rxpacket_error(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int errbit;
    const char *keywords[] = {"errbit", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &errbit)) {
        return NULL;
    }
    retval = dxl_get_rxpacket_error(errbit);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_get_rxpacket_error(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_set_txpacket_parameter(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int index;
    int value;
    const char *keywords[] = {"index", "value", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "ii", (char **) keywords, &index, &value)) {
        return NULL;
    }
    dxl_set_txpacket_parameter(index, value);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_set_txpacket_parameter(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);


PyObject *
_wrap_dynamixel_dxl_rx_packet()
{
    PyObject *py_retval;

    dxl_rx_packet();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_rx_packet();


PyObject *
_wrap_dynamixel_dxl_initialize(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    int deviceIndex;
    int baudnum;
    const char *keywords[] = {"deviceIndex", "baudnum", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "ii", (char **) keywords, &deviceIndex, &baudnum)) {
        return NULL;
    }
    retval = dxl_initialize(deviceIndex, baudnum);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_dynamixel_dxl_initialize(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);

static PyMethodDef dynamixel_functions[] = {
    {(char *) "dxl_read_word", (PyCFunction) _wrap_dynamixel_dxl_read_word, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_write_word", (PyCFunction) _wrap_dynamixel_dxl_write_word, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_txrx_packet", (PyCFunction) _wrap_dynamixel_dxl_txrx_packet, METH_NOARGS, NULL },
    {(char *) "dxl_get_lowbyte", (PyCFunction) _wrap_dynamixel_dxl_get_lowbyte, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_get_rxpacket_parameter", (PyCFunction) _wrap_dynamixel_dxl_get_rxpacket_parameter, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_read_byte", (PyCFunction) _wrap_dynamixel_dxl_read_byte, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_get_rxpacket_length", (PyCFunction) _wrap_dynamixel_dxl_get_rxpacket_length, METH_NOARGS, NULL },
    {(char *) "dxl_write_byte", (PyCFunction) _wrap_dynamixel_dxl_write_byte, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_get_result", (PyCFunction) _wrap_dynamixel_dxl_get_result, METH_NOARGS, NULL },
    {(char *) "dxl_set_txpacket_length", (PyCFunction) _wrap_dynamixel_dxl_set_txpacket_length, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_tx_packet", (PyCFunction) _wrap_dynamixel_dxl_tx_packet, METH_NOARGS, NULL },
    {(char *) "dxl_get_highbyte", (PyCFunction) _wrap_dynamixel_dxl_get_highbyte, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_ping", (PyCFunction) _wrap_dynamixel_dxl_ping, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_set_txpacket_id", (PyCFunction) _wrap_dynamixel_dxl_set_txpacket_id, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_makeword", (PyCFunction) _wrap_dynamixel_dxl_makeword, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_terminate", (PyCFunction) _wrap_dynamixel_dxl_terminate, METH_NOARGS, NULL },
    {(char *) "dxl_set_txpacket_instruction", (PyCFunction) _wrap_dynamixel_dxl_set_txpacket_instruction, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_get_rxpacket_error", (PyCFunction) _wrap_dynamixel_dxl_get_rxpacket_error, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_set_txpacket_parameter", (PyCFunction) _wrap_dynamixel_dxl_set_txpacket_parameter, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "dxl_rx_packet", (PyCFunction) _wrap_dynamixel_dxl_rx_packet, METH_NOARGS, NULL },
    {(char *) "dxl_initialize", (PyCFunction) _wrap_dynamixel_dxl_initialize, METH_KEYWORDS|METH_VARARGS, NULL },
    {NULL, NULL, 0, NULL}
};


PyMODINIT_FUNC
#if defined(__GNUC__) && __GNUC__ >= 4
__attribute__ ((visibility("default")))
#endif
initdynamixel(void)
{
    PyObject *m;
    PyObject *submodule;
    m = Py_InitModule3((char *) "dynamixel", dynamixel_functions, NULL);
    if (m == NULL) {
        return;
    }
    submodule = initdynamixel_std();
    if (submodule == NULL) {
        return;
    }
    Py_INCREF(submodule);
    PyModule_AddObject(m, (char *) "std", submodule);
}
